# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Introduction to Biological Informatics
description:      'Where Biology Becomes Genomics'
url:              http://www.datacarpentry.org/semester-biology
baseurl:          /semester-biology
email:            peter.r.hoyt@okstate.edu
feedbackurl:      polleverywhere.com/multiple_choice_polls/KznOEBvSAnahmt7
author:
  name:           'Peter R. Hoyt'
  url:            https://twitter.com/peterrhoyt

github:
  repo:           https://github.com/datacarpentry/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
