# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Introduction to Biological Informatics
description:      'Where Biology Becomes Genomics'
url:              https://github.com/hoytpr/bioinformatics-semester
baseurl:          /semester-biology
email:            peter.r.hoyt@okstate.edu
feedbackurl:      
author:
  name:           'Peter R. Hoyt'
  url:            https://twitter.com/peterrhoyt

github:
  repo:           https://github.com/hoytpr/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'
